### ISSUE TITLE
Support for ID's on layers

### ISSUE THREAD

**Issue by misterbooth** [Pixofield/keyshape-lottie-format#1]
Include Lottie layers "ln" (ID) in Json output utilising the KeyShape layers id.

**Comment by Pixofield** [comment]
Thanks for opening this issue. The 'ln' property will be useful when elements in Lottie-web SVG animations need to be accessed by JavaScript.

I've modified the exporter to write out the 'ln' property. The importer has been changed to use the 'ln' property as id, if it is given.

The changes are already in GitHub, but there are few other changes I'd like to make to this plugin before creating a new release.

If you want to use the changes already now, then you can update your Lottie plugin by manually copying exporter.js and importer.js to your local Keyshape plugin folder. You can find the Keyshape plugin folder by selecting "Reveal Plugins Folder in Finder" in the "Manage Plugins" dialog in Keyshape. The files should be copied to the "lottie-format" folder.

I'll keep this issue open until a new release has been made.

**Comment by Pixofield** [comment]
Lottie plugin version 1.3.0 has been released and it includes outputting ids.
