### ISSUE TITLE
Plugin link broken on Releases 

### ISSUE THREAD

**Issue by thesagrotan** [Pixofield/keyshape-lottie-format#10]
The link to download the plugin is broken. 
https://github.com/Pixofield/keyshape-lottie-format/releases

**Comment by Pixofield** [comment]
Can you be more specific how it is broken?

I just went to the page and it opens the Releases page as expected. On that page, clicking the latest 'Lottie-format.keyshapeplugin' file downloads the plugin.

The [home page](https://github.com/Pixofield/keyshape-lottie-format#installing) has instructions for it:

1. Go to [Releases](https://github.com/Pixofield/keyshape-lottie-format/releases) and download Lottie-format.keyshapeplugin

**Comment by thesagrotan** [comment]
I just checked it and it's working again. Thank you for the quick response.
