### ISSUE TITLE
Linking to parent

### ISSUE THREAD

**Issue by pnewell** [Pixofield/keyshape-lottie-format#14]
When I import a Lottie file, cases where multiple children share a parent just duplicates all the parents for every child. This means edits in one parent don't affect other iterations. In Adobe After Effects you can select a Parent to link to instead of actually nesting it. This allows children to be nested in an any order regardless of if they share the same parent structure. Is this feature possible with keyshape?

<img width="526" alt="Screenshot 2022-12-17 at 12 42 41 PM" src="https://user-images.githubusercontent.com/6485697/208254548-fb340067-34bc-4044-802d-70d670ef7205.png">

**Comment by Pixofield** [comment]
Keyshape is primarily an SVG animation tool. The Lottie plugin is an extension for it to enable some kind of support for Lottie files.

Unfortunately, SVG doesn't support parenting the same way After Effects and Lottie files do it. It means that Keyshape doesn't support parenting.

**Comment by pnewell** [comment]
Is there a better workflow to handle this scenario. Effectively multiple visible items whose shape/size/movement is the same, but they may need to be layered independently of one another? Or is the best option just duplicating and manually trying to keep it the same?

As a feature, could I recommend a superficial linking of effects? Kind of like a Symbol, but for one or more effects, and then I could reuse/apply those.

The original way I thought to try it was to make a Symbol with the effects I want to share amongst multiple layers, and then nest things underneath instances of the symbol, but that wasn't possible

(Mainly asking as I am a big fan of Keyshape so far, trialing it at the moment, and after 20-30 hours with it this feels like the main missing thing for me, I don't necessarily care how the problem is solved, but having no way to lock/link these parent effects ultimately adds lots of risk of accidentally ruining/messing up complex animation flows)

**Comment by Pixofield** [comment]
The only way to reuse the same animation for multiple items is to group the items and animate the group. That works for transform and opacity animations. There isn't any other way to reuse the same animation for many items.

Keyshape is a fairly simple animation tool and that's why most users like it. I'm afraid that adding more features might make it too complicated for most users. So, I probably won't be adding your suggestion about linking of effects.
