### ISSUE TITLE
Lottie error

### ISSUE THREAD

**Issue by ptichkagrif** [Pixofield/keyshape-lottie-format#2]
Hey, I have some trouble with exporting simple animation as Lottie. 

Plugin JavaScript Error (line 147, col 47):
TypeError: Cannot read property 'value' of undefined
    at valueOrAnimationMultiDim (exporter.js:147:48)
    at addShape (exporter.js:718:23)
    at appendLayer (exporter.js:851:9)
    at createJsonAndCopyAssets (exporter.js:1020:9)
    at exportAnimation (exporter.js:1062:16)

**Comment by ptichkagrif** [comment]
I just realised that Lottie can export if a file has width changes

**Comment by Pixofield** [comment]
Thanks for reporting the issue.

There was a bug in width and height property animations. It has been fixed in the Lottie plugin version 1.3.1. Could you download the new version from [Releases](https://github.com/Pixofield/keyshape-lottie-format/releases) and try it?
