### ISSUE TITLE
Intersecting paths in typography

### ISSUE THREAD

**Issue by foguetes** [Pixofield/keyshape-lottie-format#5]
When importing Lottie animations, typography with intersecting paths does not display correctly:

<img width="1013" alt="rocket" src="https://user-images.githubusercontent.com/25814516/66992983-1a31a800-f0cb-11e9-86bd-c1962557407b.png">

This can be fixed by selecting the paths and combining them with a subtract operation.

However, this has to be painstakingly done one by one.

Is this possible to fix?

You can download the Lottie file from here: [https://app.box.com/s/hw828yzceoq3oz9kxuf7hr53fygqify5](url)

**Comment by Pixofield** [comment]
Thanks for pointing out that issue. The importer doesn't support combined paths correctly. This is a bug and should be fixed.

**Comment by Pixofield** [comment]
This has been fixed in the latest Lottie plugin version 1.6.0. Note that the new version requires Keyshape 1.10 to run.
