### ISSUE TITLE
Importer does not preserve speed curves

### ISSUE THREAD

**Issue by foguetes** [Pixofield/keyshape-lottie-format#6]
When I import a Lottie json into Keyshape, the speed curves in the animation are converted to linear keyframes.

You can see the difference here:
[https://lottiefiles.com/share/Rs1CuX](url)
https://app.box.com/s/p2ai0v9wkfz49vbx9xo7pqkgq5ecqr7l

**Comment by Pixofield** [comment]
You are right. There seems to be some issues with position speed curves.

**Comment by foguetes** [comment]
Thank you for listening. Do you think these requests will be implemented in the next release?

**Comment by Pixofield** [comment]
Let's see if there is enough time to implement them.

**Comment by Pixofield** [comment]
This has been fixed in the latest Lottie plugin version 1.6.0.
